<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Eccube\Entity\CustomerLevelDetail;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CustomerLevelDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerLevelDetailRepository extends AbstractRepository
{
    /**
     * CustomerLevelDetailRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, CustomerLevelDetail::class);
    }

    /**
     * お届け先を削除します.
     *
     * @param \Eccube\Entity\CustomerLevelDetail $CustomerLevelDetail
     */
    public function delete($CustomerLevelDetail)
    {
        $em = $this->getEntityManager();
        $em->remove($CustomerLevelDetail);
        $em->flush($CustomerLevelDetail);
    }
    
    /**
     * @param int $id
     *
     * @return CustomerLevelDetail
     */
    public function get($id = 1)
    {
        $CustomerLevelDetail = $this->find($id);

        if (null === $CustomerLevelDetail) {
            throw new \Exception('CustomerLevelDetail not found. id = '.$id);
        }

        return $this->find($id);
    }

    


}
