<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Eccube\Entity\CustomerShop;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CustomerShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerShopRepository extends AbstractRepository
{
    /**
     * CustomerShopRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, CustomerShop::class);
    }

    public function newCustomerShop()
    {
        $CustomerShop = new \Eccube\Entity\CustomerShop();
        return $CustomerShop;
    }

    /**
     * お届け先を削除します.
     *
     * @param \Eccube\Entity\CustomerShop $CustomerShop
     */
    public function delete($CustomerShop)
    {
        $em = $this->getEntityManager();
        $em->remove($CustomerShop);
        $em->flush($CustomerShop);
    }
    
    /**
     * @param int $id
     *
     * @return CustomerShop
     */
    public function get($id = 1)
    {
        $CustomerShop = $this->find($id);

        if (null === $CustomerShop) {
            throw new \Exception('CustomerShop not found. id = '.$id);
        }

        return $this->find($id);
    }

    /**
     * @param  \Eccube\Entity\Customer $Customer
     *
     * @return CustomerShop
     */

    public function getCustomerShopByCustomer(\Eccube\Entity\Customer $Customer)
    {      
        try {   
            $qb = $this->createQueryBuilder('cfp')
            ->where('cfp.Customer = :Customer')
            ->setParameter('Customer', $Customer);
            $CustomerShop = $qb->getQuery()->getSingleResult();
            return $CustomerShop;
        }
        catch (\Doctrine\Orm\NoResultException $e) {   
              return null;
          }



    }


}
