<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Eccube\Entity\CustomerLevel;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CustomerLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerLevelRepository extends AbstractRepository
{
    /**
     * CustomerLevelRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, CustomerLevel::class);
    }

    /**
     * お届け先を削除します.
     *
     * @param \Eccube\Entity\CustomerLevel $CustomerLevel
     */
    public function delete($CustomerLevel)
    {
        $em = $this->getEntityManager();
        $em->remove($CustomerLevel);
        $em->flush($CustomerLevel);
    }
    
    /**
     * @param int $id
     *
     * @return CustomerLevel
     */
    public function get($id = 1)
    {
        $CustomerLevel = $this->find($id);

        if (null === $CustomerLevel) {
            throw new \Exception('CustomerLevel not found. id = '.$id);
        }

        return $this->find($id);
    }

    /**
     * @param  \Eccube\Entity\Customer $Customer
     *
     * @return CustomerLevel
     */

    public function getCustomerLevelByCustomer(\Eccube\Entity\Customer $Customer)
    {     
        try {    
            $qb = $this->createQueryBuilder('cfp')
            ->where('cfp.Customer = :Customer')
            ->setParameter('Customer', $Customer);
            return $qb->getQuery()->getSingleResult();
        }
        catch (\Doctrine\Orm\NoResultException $e) {   
              return null;
        }


    }


}
