<?php

namespace Plugin\SSNext;

use Doctrine\ORM\EntityManager;
use Eccube\Entity\Csv;
use Eccube\Entity\Master\CsvType;
use Eccube\Entity\Product;
use Eccube\Entity\ProductClass;
use Eccube\Plugin\AbstractPluginManager;
use Eccube\Repository\CsvRepository;
use Eccube\Repository\Master\CsvTypeRepository;
use Symfony\Component\DependencyInjection\ContainerInterface;

class PluginManager extends AbstractPluginManager
{

    const CSV_TYPE = 7001;

    public function enable(array $meta, ContainerInterface $container)
    {
        /** @var EntityManager $entityManager */
        $entityManager = $container->get('doctrine.orm.entity_manager');
        /** @var CsvTypeRepository $csvTypeRepository */
        $csvTypeRepository = $entityManager->getRepository(CsvType::class);
        if (!$csvTypeRepository->find(self::CSV_TYPE)) {
            $csvType = new CsvType();
            $csvType->setId(self::CSV_TYPE);
            $csvType->setName("ネクストエンジン商品CSV");
            $csvType->setSortNo($csvTypeRepository->findOneBy([], ['sort_no' => 'DESC'])->getSortNo()+1);

            $csvTypeRepository->save($csvType);

            $csv = new Csv();
            $csv->setCsvType($csvType);
            $csv->setEnabled(true);

            //$csv->setEntityName('Eccube\\\Entity\\\ProductClass');
            //$csv->setDispName("product_class_id");
            //$csv->setFieldName("id");
            //$csv->setSortNo(1);
            //$entityManager->persist($csv);

            $csv = clone $csv;
            $csv->setEntityName('Eccube\\\Entity\\\ProductClass');
            $csv->setDispName("商品コード");
            $csv->setFieldName("code");
            $csv->setSortNo(1);
            $entityManager->persist($csv);

            $csv = clone $csv;
            $csv->setEntityName('Eccube\\\Entity\\\Product');
            $csv->setDispName("商品名");
            $csv->setFieldName("name");
            $csv->setSortNo(2);
            $entityManager->persist($csv);

            $csv = clone $csv;
            $csv->setEntityName('Eccube\\\Entity\\\ProductClass');
            $csv->setDispName("売価");
            $csv->setFieldName("price02");
            $csv->setSortNo(3);
            $entityManager->persist($csv);

        }

        parent::enable($meta, $container); // TODO: Change the autogenerated stub
    }

    public function uninstall(array $meta, ContainerInterface $container)
    {
        parent::uninstall($meta, $container); // TODO: Change the autogenerated stub

        /** @var EntityManager $entityManager */
        $entityManager = $container->get('doctrine.orm.entity_manager');
        /** @var CsvTypeRepository $csvTypeRepository */
        $csvTypeRepository = $entityManager->getRepository(CsvType::class);

        $csvType = $csvTypeRepository->find(self::CSV_TYPE);

        if ($csvType) {
            $entityManager->beginTransaction();

            /** @var CsvRepository $csvRepository */
            $csvRepository = $entityManager->getRepository(Csv::class);
            $csvCol = $csvRepository->findBy(['CsvType' => $csvType]);

            if ($csvCol && count($csvCol)) {
                foreach ($csvCol as $val) {
                    $csvRepository->delete($val);
                }
            }

            $csvTypeRepository->delete($csvType);

            $entityManager->flush();

            $entityManager->commit();
        }
    }
}