<?php

namespace Plugin\SoftbankPayment4\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\SoftbankPayment4\Entity\SbpsTradeDetail;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * SbpsTradingDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SbpsTradeDetailRepository extends AbstractRepository
{
    /**
     * SbpsTradingRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, SbpsTradeDetail::class);
    }
}
